# Generated by Django 4.2.5 on 2023-09-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mover', '0002_alter_booking_dropoff_location_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
