# Generated by Django 4.2.5 on 2023-09-11 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mover', '0003_alter_customuser_managers_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
