# Generated by Django 4.2.5 on 2023-09-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mover', '0014_booking_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_accepted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
