# Generated by Django 4.2.5 on 2023-09-29 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mover', '0015_booking_is_accepted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='is_fufuilled',
            new_name='is_fulfilled',
        ),
    ]
