# Generated by Django 4.2.5 on 2023-10-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mover', '0016_rename_is_fufuilled_booking_is_fulfilled'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('SUV', 'SUV'), ('MiniVan', 'MiniVan'), ('Cargo Van', 'Cargo Van'), ('Pick Up Truck', 'Pick Up Truck')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Goods',
        ),
    ]
