# Generated by Django 4.2.5 on 2023-10-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mover', '0019_booking_total_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='estimated_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
