# Generated by Django 4.2.5 on 2023-10-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mover', '0020_booking_estimated_duration_booking_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address_latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='address_longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='minutes_away',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
