# Generated by Django 4.2.6 on 2023-12-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mover', '0024_customuser_drivers_license_back_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='drivers_license',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_photo',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='exterior_back_vehicle_photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='exterior_front_vehicle_photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='exterior_side_vehicle_photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
